name: Build and Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore NuGet packages
      run: dotnet restore

    - name: Build for Windows
      run: dotnet build -c Release
      if: runner.os == 'windows'

    - name: Build for macOS
      run: dotnet build -c Release
      if: runner.os == 'macos'

    - name: Build for Linux
      run: dotnet build -c Release
      if: runner.os == 'linux'

    - name: Copy artifacts to workspace
      run: |
        mkdir -p ${{ github.workspace }}/artifacts
        cp -r ${{ github.workspace }}/OsuCollectionDownloader/bin/Release ${{ github.workspace }}/artifacts
      if: always()
  upload:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Upload Release
      uses: actions/upload-artifact@v3
      with:
        name: Release
        path: $GITHUB_WORKSPACE/artifacts
