name: Build and Release

on:
  push:
    branches:
      - master

jobs:
  windows_build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore NuGet packages
      run: dotnet restore

    - name: Build for Windows
      run: dotnet publish -c Release

    - name: Upload Release Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Release (Windows)
        path: D:\a\OsuCollectionDownloader\OsuCollectionDownloader\OsuCollectionDownloader\bin\Release\net8.0\win-x64\publish\

  macos_build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install required dependencies for AOT publishing
      run: brew install llvm-objcopy

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore NuGet packages
      run: dotnet restore

    - name: Build for macOS
      run: dotnet publish -c Release

    - name: Upload Release Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Release (MacOS)
        path: /Users/runner/work/OsuCollectionDownloader/OsuCollectionDownloader/OsuCollectionDownloader/bin/Release/net8.0/linux-x64/publish/

  linux_build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore NuGet packages
      run: dotnet restore

    - name: Build for Linux
      run: dotnet publish -c Release

    - name: Upload Release Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Release (Linux)
        path: /home/runner/work/OsuCollectionDownloader/OsuCollectionDownloader/OsuCollectionDownloader/bin/Release/net8.0/linux-x64/publish/
